config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  
  namespace :api do
    get '/users/:user_id/posts', to: 'posts#index'
    post '/comments', to: 'comments#create'
    get '/users/:user_id/posts/:post_id/comments', to: 'comments#index'
  end

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
  end

  devise_for :users, skip: :all
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  post "users/:user_id/posts", to: "posts#create", as: :user_create_post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :comments
  has_many :posts
  has_many :likes

  validates :name, presence: true

  # has_one_attached :photo # Add this line to handle the photo attachment

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end

  def user_has_liked?(post, user)
    likes.exists?(post:, user:)
  end

  def remove_user_like(post, user)
    likes.find_by(post:, user:).destroy
  end

  def add_user_like(post, user)
    likes.create(post:, user:)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.includes(:posts).find(params[:id])
    @posts = @user.recent_post
    @post_counter = @user.posts.length
  end

  def index
    @users = User.all
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def render_user(user)
    content_tag(:li, class: 'user-container') do
      concat(content_tag(:div, class: 'user-profile-pic') do
        link_to(user_path(user)) do
          image_tag(user.photo || '', alt: 'profile-picture')
        end
      end)
      concat(content_tag(:div, class: 'user-info') do
        concat(content_tag(:h3) do
          link_to(user.name, user_path(user))
        end)
        concat(content_tag(:p, class: 'posts-counter') do
          "Number of posts: #{user.posts_counter || 0}"
        end)
      end)
    end
  end

  def render_post(user, post)
    link_to(user_post_path(user, post)) do
      content_tag(:div, class: 'post-container') do
        concat(content_tag(:h3, post.title, class: 'post-title'))
        concat(content_tag(:div, class: 'post-details') do
          content_tag(:p, truncate(post.text, length: 100, omission: '...'), class: 'details')
        end)
        concat(content_tag(:div, class: 'comment-like-container') do
          content_tag(:p, class: 'coment-likes-data') do
            "Comments: #{post.comment_counter || 0}, Likes #{post.likes_counter || 0}"
          end
        end)
      end
    end
  end
end

app/views/users/index.html.erb
<div id="home" class="page">
  <div id="user-page">
    <div class="btn-container">
      <%= link_to raw('<i class="fas fa-house"></i>'), root_path %>
    </div>
    <div class="signout-container">
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "signout-link" %>
    </div>
    <h1>Welcome <span class='current-user'><%= current_user.name %>!</span> <i class="fa-solid fa-users"></i></h1>


    <ul class="users-list">
      <%= @users.map { |user| render_user(user) }.join.html_safe %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div id="user-index" class="page">
  <%# Home button start %>
  <div id="user-page">
    <div class="btn-container">
      <%= link_to raw('<i class="fas fa-house"></i>'), "../../" %>
    </div>
    <%# End fo Home button  %>

    <%# display create post link if user is signed in %>
    <% if current_user == @user %>
      <div class="btn-container">
        <%= link_to "Create post", new_user_post_path(@user) %>
      </div>
    <% end %>
    
    <%# user info start %>
    <div class="user-container">
      <div class="user-profile-pic">
        <img src="<%= @user.photo %>" alt="profile-picture">
      </div>
      <div class="user-info">
        <h3><%= @user.name%></h3>
        <p class="posts-counter">Number of posts: <%= @user.posts_counter || 0 %></p>
      </div>
    </div>
    <article class="user-bio">
      <h3>Bio</h3>
      <div class="bio"><%= @user.bio %></div>
    </article>
    <%# end of user info %>
    <%# posts start %>
    <article>
      <%= @posts.map { |post| render_post(@user, post) }.join.html_safe %>
    </article>
    <%# end of post %>
  
    <% if @post_counter > 3 %>
          <div class="btn-container see-posts">
            <%= link_to "See all posts", user_posts_path(@user) %>
          </div>
      <%end%>
    
    <%# end of see all button %>
  </div>
</div>