config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  
  namespace :api do
    get '/users/:user_id/posts', to: 'posts#index'
    post '/comments', to: 'comments#create'
    get '/users/:user_id/posts/:post_id/comments', to: 'comments#index'
  end

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
  end

  devise_for :users, skip: :all
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  post "users/:user_id/posts", to: "posts#create", as: :user_create_post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 250 }
  validates :comment_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :text, presence: true, length: { minimum: 3, maximum: 250 }
  after_create :post_count_updater
  after_destroy :post_count_updater

  def post_count_updater
    user.update(posts_counter: user.posts.count)
  end

  def recent_comments
    comments.includes(:user).order(created_at: :desc).limit(5)
  end
end

app/controllers/api/posts_controller.rb
module Api
  class Api::PostsController < ApiController
    def index
      @user = User.find(params[:user_id])
      @posts = Post.where(user_id: @user.id).includes(:comments)
      render json: @posts
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def new
    @current_user = current_user
    @post = Post.new
  end

  def create
    @post = Post.new(title: post_params[:title], text: post_params[:text], user_id: current_user[:id],
                     comment_counter: 0, likes_counter: 0)

    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post created successfully.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @comments = Comment.where(post_id: params[:id])
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to user_posts_path(current_user, @post), notice: 'Post was successfully destroyed.'
  end

  def include_user
    @user = User.includes(:posts, posts: [:comments, { comments: [:author] }]).find(params[:user_id])
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_comment_delete_button(user, post, comment)
    button_to user_post_comment_path(user, post, comment),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: 'del-post-btn' do
      submit_tag '|Delete', title: 'delete comment', id: 'delete'
    end
  end

  def render_few_comment(post, user)
    content_tag(:ul, class: 'post-comments-container') do
      if post.recent_comments.any?
        post.recent_comments.each do |comment|
          concat(content_tag(:li, class: 'comment-box') do
            concat(content_tag(:p) do
              user_name = comment.user.name
              user_comment = truncate(comment.text, length: 60, omission: '...')
              comment_content = "#{user_name}: #{user_comment}".html_safe
              concat(comment_content)
              concat(render_comment_delete_button(user, post, comment)) if can? :destroy, comment
            end)
          end)
        end
      else
        content_tag(:li, 'No comments added yet')
      end
    end
  end

  def render_posts(user, post)
    link_to(user_post_path(user, post)) do
      content_tag(:div, class: 'post-containe') do
        concat(content_tag(:h3, post.title, class: 'post-title'))
        concat(content_tag(:div, class: 'post-details') do
          content_tag(:p, truncate(post.text, length: 100, omission: '...'), class: 'details')
        end)
        concat(content_tag(:div, class: 'comment-like-container') do
          content_tag(:p, class: 'coment-likes-data container') do
            comment = post.comment_counter || 0
            likes = post.likes_counter || 0
            "Comments: #{comment}, Likes: #{likes}"
          end
        end)
        concat(render_few_comment(post, user))
      end
    end
  end

  def render_all_comment(user, post, comments)
    if comments.any?
      safe_join(comments.map do |comment|
        content_tag(:li, class: 'comment-box') do
          content_tag(:p) do
            user_name = User.find_by(id: comment.user_id)&.name
            user_comment = comment.text
            comment_content = "#{user_name}: #{user_comment}".html_safe
            concat(comment_content)
            concat(render_comment_delete_button(user, post, comment)) if can? :destroy, comment
          end
        end
      end)
    else
      content_tag(:li, 'No comments added yet..')
    end
  end
end

app/views/posts/index.html.erb
<div id="posts" class="page">
  <%# Home button start %>
  <div id="user-page">
    <div class="btn-container">
      <%= link_to raw('<i class="fas fa-house"></i>'), "../../" %>
    </div>
  </div>
  <%# End fo Home button  %>
  <%# user profile start %>
  <div class="user-container posts">
    <div class="user-profile-pic">
      <img src="<%= @user.photo || '' %>" alt="profile-picture">
    </div>
    <div class="user-info">
      <h3><%= @user.name%></h3>
      <p class="posts-counter">Number of posts: <%= @user.posts_counter || 0 %></p>
    </div>
  </div>
  <%# End of user profile %>
  <article class="posts-container">
    <% @posts.each do |post| %>
    <%= render_posts(@user, post) %>
  <% end %>
  </article>
</div>

app/views/posts/new.html.erb
<div class="page" id="post-form-page" >
    <h1>Create New Post</h1>
    <%= form_with(model: @post, url:  user_create_post_path, method: :post, remote: false ) do |f| %>
      <div class="post-inputs">
        <%= f.label :title %>
        <%= f.text_field :title, required: true, autofocus: true,  pattern: ".{5,}", title: "Title must be at least 5 characters", placeholder: "Enter Post Title"  %>
      </div>
      <div class="post-inputs">
        <%= f.label :text  %>
        <%= f.text_area :text, resize: "none", required: true, pattern: ".{5,}", title: "Please fill out this are", placeholder: "Enter Text"  %>
      </div>
        <%= f.submit "Create Post" %>
    <% end %>
</div>

app/views/posts/show.html.erb
<div id="post-index" class="page">
  <div id="user-page">
    <%# Home button start %>
    <div class="btn-container">
      <%= link_to raw('<i class="fa-solid fa-house"></i>'), "../../" %>
    </div>
    <%# End fo Home button  %>
    <div class="single-post-container">
      <%# user post start %>
      <article class="post-article">
        <div class="info">
          <section class="flex">
            <div>
              <h2 class="title"><%= @post.title %></h2>
              <p class="user-name">by <%= @user.name %></p>
            </div>
            <%# Delete post btn%>
            <div>
              <% if can? :destroy, @post %>
              <%= button_to user_post_path(@user, @post), method: :delete, data: { confirm: 'Are you sure?' }, id: 'dell-post-btn' do %>
                <%= hidden_field_tag :id, @post.id %>
                <%= submit_tag 'delete post'%>
              <% end %>
            <% end %>
            </section>
            <%# End of Delete post btn%>
          <div>
          <p class="posts-counter">
            Comment: <%= @post.comment_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %>
          </div>
          <div class="post-body">
            <p><%= @post.text %></p>
          </div>
        </article>
        <%# End of user post %>
        <div class="interaction">
          <%= form_with(model: @like, url: user_post_likes_path(@user, @post), method: :post) do |form| %>
            <div class="add-coment-btn">
              <%= form.hidden_field :post_id, value: @post.id %>
              <%= form.submit "Like" %>
            </div>
          <% end %>


          <%# %>
          <%# Create comment button %>
          <div class="btn-container">
            <%= link_to "Add comment", new_user_post_comment_path(@user, @post) %>
          </div>
          <%# End of Create comment button %>
        </div>
       
        <%# Comments container start %>
        <ul class="comments-container">
          <%= render_all_comment(@user, @post, @post.comments) %>
        </ul>
        <%# End of Comments container  %>
      </div>
    </div>
  </div>